# Generated by Django 4.0 on 2022-02-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task21', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
