# Generated by Django 4.0 on 2022-02-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task21', '0003_alter_person_age_alter_person_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(help_text='Введите возраст', verbose_name='Возраст'),
        ),
    ]
