# Generated by Django 4.0.2 on 2022-02-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='login',
            field=models.CharField(max_length=50, null=True, verbose_name='Login'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=50, null=True, verbose_name='Password'),
        ),
    ]
