# Generated by Django 4.0.2 on 2022-02-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0002_myuser_email_myuser_login_myuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=50, null=True, verbose_name='E-mail'),
        ),
    ]
