# Generated by Django 4.0.2 on 2022-02-23 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=200, verbose_name='Product name')),
                ('supplier', models.CharField(blank=True, help_text='Supplier', max_length=100, null=True, verbose_name='Date of supplying')),
                ('current_amont', models.IntegerField(help_text='Current amount', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Current amount')),
                ('update_date', models.DateTimeField(auto_now_add=True, help_text='Update date', verbose_name='Date of update')),
            ],
        ),
    ]
