# Generated by Django 3.2.12 on 2022-02-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254),
        ),
        migrations.AddField(
            model_name='myuser',
            name='login',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='myuser',
            name='password',
            field=models.CharField(default='', max_length=32),
        ),
    ]
