version: "3"

services:
  server:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    tty: true
    volumes:
      - .:/auth2
    ports:
      - 80:8000
    environment:
      - POSTGRES_NAME=auth2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth2

volumes:
  postgres_data: